= Developing the Disruptor

:Author: LMAX Development Team
:Email:
:Date: {docdata}

A guide to checking out the code, building it and running the performance tests

== Getting Started

We have switched from ant to gradle. More detailed instructions on how to work on the disruptor using gradle will follow. To get started list the available tasks by issuing:

[source,shell script]
----
$ ./gradlew tasks
----

and take it from there.

No gradle install is necessary as gradle is self-provisioning.

== Basic workflow
1. Check out the project locally to your machine
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}
$ git clone git://github.com/LMAX-Exchange/disruptor.git
----
--

2. Build a distribution
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}/disruptor
$ ./gradlew
----
As a result of the build you should find the following files:

 - `${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT.jar`
 - `${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT-javadoc.jar`
 - `${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT-sources.jar`
--

3. Run the performance tests
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}/disruptor
$ ./gradlew perfJar
$ java -cp build/libs/disruptor-perf-3.3.0.jar [test name, e.g. com.lmax.disruptor.sequenced.OneToOneSequencedThroughputTest]
----

There are also JMH Benchmarks for testing the performance of the Disruptor, these can be run with a gradle command

[source,shell script]
----
$ ./gradlew jmh
----
--

4. Development tips
+
--
This project uses GitHub Actions for CI which runs the gradle build task to check the project can be built on each
commit/pull request.

So that you don't push changes that will fail the simple test & check steps we would suggest adding the git pre-commit
hook which will block any commit you try to do locally if the code fails these steps.

The git hook can be set up using the following gradle task:

[source,shell script]
----
$ ./gradlew setUpGitHooks
----
--

// Todo: coding standards?