= Developing the Disruptor

:Author: LMAX Development Team
:Email:
:Date: {docdata}

A guide to checking out the code, building it and running the performance tests

== Getting Started

We have switched from ant to gradle. More detailed instructions on how to work on the disruptor using gradle will follow. To get started list the available tasks by issuing:

[source,shell script]
----
$ ./gradlew tasks
----

and take it from there.

No gradle install is necessary as gradle is self-provisioning.

== Basic workflow
1. Check out the project locally to your machine
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}
$ git clone git://github.com/LMAX-Exchange/disruptor.git
----
--

2. Build a distribution
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}/disruptor
$ ./gradlew
----
As a result of the build you should find the following files:

${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT.jar
${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT-javadoc.jar
${MY_PROJECTS_HOME}/disruptor/build/libs/disruptor-{VERSION_NUMBER}-SNAPSHOT-sources.jar
--

3. Run the performance tests
+
--
[source,shell script]
----
$ cd ${MY_PROJECTS_HOME}/disruptor
$ ./gradlew perfJar
$ java -cp build/libs/disruptor-perf-3.3.0.jar [test name, e.g. com.lmax.disruptor.sequenced.OneToOneSequencedThroughputTest]
----
--

// Todo: coding standards?