= Publishing Release

:Author: LMAX Development Team
:Email:
:Date: {docdata}

== Prerequisites

1. All tests should be completing successfully in CI and locally
2. The changelog is updated with relevant information
3. `build.gradle` has been updated with the version information for the proposed release, and pushed to GitHub
4. Create a new release via GitHub UI, this should tag the commit

== GPG Key

To sign the artifact, a requirement for public release, you must have a signing GPG key set up.

=== Creating a new GPG signing key

If you already have a GPG signing key, you can skip to the next section.

- If you are on version 2.1.17 or greater, paste the text below to generate a GPG key pair:
+
--
[source,shell script]
----
$ gpg --full-generate-key
----
  - At the prompt, specify the kind of key you want, or press Enter to accept the default RSA and RSA.
  - Enter the desired key size. Your key must be at least 4096 bits.
  - Enter the length of time the key should be valid. Press Enter to specify the default selection, indicating that the key doesn't expire.
  - At the prompt, specify the kind of key you want, or press Enter to accept the default RSA and RSA
  - At the prompt, specify the kind of key you want, or press Enter to accept the default RSA and RSA
--

 - If you are not on version 2.1.17 or greater, the `gpg --full-generate-key` command doesn't work:
+
--
[source,shell script]
----
$ gpg --default-new-key-algo rsa4096 --gen-key
----
--

 - Verify that your selections are correct.
 - Enter your user ID information.
 - Type a secure passphrase.
 - (is using gpg >= 2.1) Export the keyring to a gpg file
+
--
[source,shell script]
----
gpg --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg
----
--

=== Adding signing options for gradle

 - `signing.keyId` is the last 8 characters of the public key id for the signing key, in this example, `9F712BEC`.
 - `signing.password` is the passphrase for your keyring
 - `signing.secretKeyRingFile` is the absolute path to the secret key ring file containing your private key

[source,shell script]
----
$ gpg --list-secret-keys --keyid-format SHORT
/home/dev/.gnupg/pubring.kbx
-----------------------------
sec   rsa4096/9F712BEC 2021-04-13 [SC]
      6B76BC6777E78FB33B2C2D0A3A7EE8C49F712BEC
uid         [ultimate] LMAX Coder (LMAX Developer) <coders@lmax.com>
ssb   rsa4096/A97D3F8A 2021-04-13 [E]

$ cat gradle.properties
signing.keyId=9F712BEC
signing.password=<passphrase used to protect your private key>
signing.secretKeyRingFile=/home/dev/.gnupg/secring.gpg
----

See: https://docs.gradle.org/current/userguide/signing_plugin.html

=== Publish your public key

You need to publish your public key so that sonatype can verify who signed the release artifacts.

----
gpg --keyserver https://keyserver.ubuntu.com/ --send-keys 9F712BEC
----

Note: Other `keyservers` are available

== Release process

1. Clean any existing build data
+
--
[source,shell script]
----
$ ./gradlew clean
----
--
2. Add `gradle.properties` file in the root of the disruptor project with the following content
+
--
[source,shell script]
----
$ cat gradle.properties

sonatypeUsername=<username for sonatype>
sonatypePassword=<password for sonatype>
signing.keyId=<signing-key>
signing.password=<password>>
signing.secretKeyRingFile=/home/dev/.gnupg/secring.gpg
----
--
3. Build & upload to Sonatype
+
--
[source,shell script]
----
$ ./gradlew publish
----
*Note: Make sure the signing step was not skipped*
--
4. Release in to Sonatype
+
--
 - Log in to https://oss.sonatype.org/
 - Go to https://oss.sonatype.org/#stagingRepositories[Staging Repositories]
 - Verify all the files are present and correct (including `*.asc` files generated by signing)
 - Close the staging repository
 - Release the repository
 - Assuming all went well, wait to see changes at: https://repo1.maven.org/maven2/com/lmax/disruptor/
--
5. Remove `gradle.properties` file
+
--
This file is ignored from git, but I would not advise leaving it on disk long term as it has 2 passwords in plain text.
--