name: JCStress Testing - stress testing

on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jcstress -Pmode=tough
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jcstress-report-stress
          path: build/reports/jcstress
